version: "3"
services:
  test:
    build: .
    volumes:
      - .:/home/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    command: bundle exec rake
  postgres:
    image: postgres:9.6